server:
  port: ${PORT:8022}
spring:
  application:
    name: account-manager
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:devsu_account}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:h4ckm3}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
      show-sql: true
  profiles:
    active: dev
  cloud:
    config:
      label: master
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8020}
  liquibase:
    drop-first: false
    change-log: classpath:db/changelog/db.changelog-master.xml
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: account-manager
      auto-offset-reset: earliest