server:
  port: ${PORT:8020}
spring:
  application:
    name: config-server
  datasource:
    hikari:
      connection-timeout: 5000
      maximum-pool-size: 2
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${HOST_DB:localhost}:5432/devsu_config
    username: postgres
    password: h4ckm3
  cloud:
    config:
      server:
        jdbc:
          sql: SELECT PROP_KEY, PROP_VALUE from T_CONFIGURATION where APPLICATION=? and PROFILE=? and LABEL=?
  profiles:
    include: jdbc
  liquibase:
    drop-first: false
    change-log: classpath:db/changelog/db.changelog-master.xml
encrypt:
  key: mys3cr3tk3y